version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:bionic
    steps:
      - checkout
      - run:
          name: NPM Install
          command: npm install
      - run: npm run test
