apiVersion: v1alpha
metadata:
  name: Feature XYZ
  tags:
  - e2e
  - release team
  - other tag
  build: Release $CI_COMMIT_SHORT_SHA
files:
- ./tests
suites:
  - name: "default"
    match: ".*.(spec|test).js$"
fileTransfer: mount
image:
  base: saucelabs/stt-playwright-jest-node
  version: v0.2.1
sauce:
  region: us-west-1
